cd ../../..

cd src/tasks/343300-SyncInLoopBodies 

cd src/apps/343300-SyncInLoopBodies

dotnet run --project ./SyncInLoopBodies.csproj -- ViaTls


dotnet run --project ./SyncInLoopBodies.csproj -- ViaLock

# The following example shows a data race where an unexpected result is generated by sharing a data
# value across iterations of the loop body.
dotnet run --project ./SyncInLoopBodies.csproj -- ViaShared
